# Generated by Django 4.2.2 on 2023-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Bedsitter', 'BEDSITTER'), ('Single-room', 'SINGLE-ROOM'), ('Double-room', 'DOUBLE-ROOM'), ('Appartment', 'APPPARTMENT'), ('1-bedroom', '1-BEDROOM'), ('2-bedroom', '2-BEDROOM'), ('3-bedroom', '3-BEDROOM'), ('4-bedroom', '4+BEDROOM'), ('Hostel', 'HOSTEL')], default='', max_length=12)),
                ('town', models.CharField(max_length=200)),
                ('specific_location', models.CharField(max_length=200)),
                ('monthly_cost', models.IntegerField()),
                ('extras', models.CharField(choices=[('Parking', 'PARKING'), ('Drawers', 'DRAWERS'), ('Sink', 'SINK'), ('Electricity', 'ELECTRICITY'), ('Security', 'SECURITY'), ('Wardrobe', 'WARDROBE'), ('Furnishing', 'FURNISHING')], default='', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created', '-type', 'monthly_cost'],
            },
        ),
    ]
