# Generated by Django 4.2.2 on 2023-06-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='extras',
            field=models.CharField(choices=[('Parking', 'PARKING'), ('Drawers', 'DRAWERS'), ('Sink', 'SINK'), ('Electricity', 'ELECTRICITY'), ('Security', 'SECURITY'), ('Wardrobe', 'WARDROBE'), ('Furnishing', 'FURNISHING')], default='', max_length=255),
        ),
    ]
