# Generated by Django 4.2.2 on 2023-06-08 14:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='extras',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Parking', 'PARKING'), ('Drawers', 'DRAWERS'), ('Sink', 'SINK'), ('Electricity', 'ELECTRICITY'), ('Security', 'SECURITY'), ('Wardrobe', 'WARDROBE'), ('Furnishing', 'FURNISHING')], default=[], max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Bedsitter', 'BEDSITTER'), ('Single-room', 'SINGLE-ROOM'), ('Double-room', 'DOUBLE-ROOM'), ('Appartment', 'APPPARTMENT'), ('1-bedroom', '1-BEDROOM'), ('2-bedroom', '2-BEDROOM'), ('3-bedroom', '3-BEDROOM'), ('4-bedroom', '4+BEDROOM'), ('Hostel', 'HOSTEL')], default=[], max_length=12),
        ),
    ]
